spring:
  main:
    banner-mode: off
  datasource:
    username: root
    password: meryemefe243
    url: jdbc:mysql://localhost:3306/messenger?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
